# syntax=docker/dockerfile:1
FROM python:3.8-slim-buster

WORKDIR /flask-app

COPY requirements-flask.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY flask ./flask 

ENTRYPOINT python flask/app.py